export const mockUser = {
  id: "user_1",
  email: "demo@devstash.io",
  name: "John Doe",
  isPro: false,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-15"),
};

export const mockItemTypes = [
  {
    id: "type_1",
    name: "snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
  },
  {
    id: "type_2",
    name: "prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
  },
  {
    id: "type_3",
    name: "command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
  },
  {
    id: "type_4",
    name: "note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
  },
  {
    id: "type_5",
    name: "file",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
  },
  {
    id: "type_6",
    name: "image",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
  },
  {
    id: "type_7",
    name: "link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: "coll_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "coll_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "coll_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "coll_4",
    name: "Interview Prep",
    description: "Resources for interview preparation",
    isFavorite: false,
    itemCount: 34,
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "coll_5",
    name: "Git Commands",
    description: "Commonly used git commands",
    isFavorite: true,
    itemCount: 7,
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "coll_6",
    name: "AI Prompts",
    description: "Curated prompts for coding",
    isFavorite: false,
    itemCount: 6,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "TEXT",
    content: "const useAuth = () => {\n  // Custom auth hook implementation\n}",
    description: "Custom authentication hook for React applications",
    isFavorite: true,
    isPinned: true,
    language: "typescript",
    itemTypeId: "type_1",
    tags: ["react", "auth", "hooks"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "TEXT",
    content: "try {\n  // API call\n} catch (error) {\n  // Handle error\n}",
    description: "Standard pattern for handling API errors",
    isFavorite: true,
    isPinned: false,
    language: "typescript",
    itemTypeId: "type_1",
    tags: ["api", "error-handling"],
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "item_3",
    title: "Code Review Prompt",
    contentType: "TEXT",
    content: "Review this code for security and performance issues...",
    description: "Prompt for AI code reviews",
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: "type_2",
    tags: ["ai", "code-review"],
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "item_4",
    title: "git reset --hard HEAD~1",
    contentType: "TEXT",
    content: "git reset --hard HEAD~1",
    description: "Reset to previous commit",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    itemTypeId: "type_3",
    tags: ["git", "reset"],
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
];

export const mockItemTypeCounts = {
  snippet: 24,
  prompt: 15,
  command: 10,
  note: 7,
  file: 4,
  image: 3,
  link: 8,
};
